errori all'apertura
mi dava degli errori appena aperto e non mi faceva avviare il gioco : 'Assets/Scripts/UI/InitialVignette.cs(111,38): error CS1061: 'GameManager' does not contain a definition for 'PrintCurrentState' and no accessible extension method 'PrintCurrentState' accepting a first argument of type 'GameManager' could be found (are you missing a using directive or an assembly reference?)